Chapter02/MySecondWebRazor/Models/Product.cs
namespace MySecondWebRazor.Models;
public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
}

Chapter02/MySecondWebRazor/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MySecondWebRazor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Chapter02/MySecondWebRazor/Pages/Index.cshtml.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySecondWebRazor.Models;

namespace MySecondWebRazor.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    public List<Product> Products { get; set; }
    public string Message { get; set; }
    public string Color { get; set; }

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
        Products = GenerateProduct(10);
        Message = "I'm using the Razor Syntax.";
    }

    public void OnGet()
    {

    }

    public void OnPost(int quantity)
    {
        Products = GenerateProduct(quantity);
    }

    public void OnGetDefineColor(int id)
    {
        Color = id == 1 ? "#FF0000" : "green";
    }

    private List<Product> GenerateProduct(int quantity) 
    {
        var random = new Random();

        var products = Enumerable.Range(1, quantity).Select(i => new Product
        {
            Id = i,
            Name = $"Product {i}",
            Price = (decimal)(random.NextDouble() * 100.0)
        }).ToList();

        return products;
    }
}

Chapter02/MySecondWebRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MySecondWebRazor.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Chapter02/MySecondWebRazor/Pages/Index.cshtml
@page
@using MySecondWebRazor.Pages.Shared
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    string subtitle = "It's funny";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p> 
    <h2>@Model.Message</h2><br />
    <h3>@subtitle</h3>
    <a asp-page-handler="DefineColor" asp-route-id="1">Red</a>
    <a asp-page-handler="DefineColor" asp-route-d="2">Green</a>
    <div style="width: 200px;height:200px;background-color:@Model.Color"></div>
    <form method="post">
        <label>Total:</label><input type="text" 
        name="quantity"/>
        <input type="submit" value="Load Products" 
        name="btn" />
    </form>
    <table class="table">
        <thead>
            <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Preço</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Products)
            {
            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td>@product.Price.ToString("C")</td>
            </tr>
            }
        </tbody>
    </table>
    <hr/>
    <!-- Integrate with Razor Components -->
    <Component type="typeof(Technology)" render-mode="ServerPrerendered" />
</div>

Chapter02/MySecondWebRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MySecondWebRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MySecondWebRazor.styles.css" asp-append-version="true" />
    <base href="~/" />
    <component type="typeof(Microsoft.AspNetCore.Components.Web.HeadOutlet)" render-mode="ServerPrerendered" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MySecondWebRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MySecondWebRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="_framework/blazor.server.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>